--- # my first playbook
- hosts: appserver
#  vars:
#  - control_server: asegretto1.mylabserver.com
#  - web_dir: /var/www/html
  vars_files:
  - my_vars.yml
  tasks:
  - name: Install Lynx on App Servers
    yum: name=lynx state=installed update_cache=true
...
