---
#My First YAML Playbook for Ansible

- hosts: all
  user: anthonysegretto
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    - playbook_version: 0.1b
  vars_files: 
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: Which package will we install?
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      notify: restart httpd
    - name: Install the Lynx Web Browser
      action: yum name={{ lynx_pkg }} state=installed
    - name: Dynamic package installation
      action: yum name={{ pkg_name }} state=installed
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
...
