- hosts: apacheweb
  user: anthonysegretto
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time of when the playbook starts
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: install the apache web server
    yum: name=httpd state=latest
    notify: start_apache
  - name: verify that the web service is running
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install client software - telnet
    yum: name=telnet state=latest
  - name: install client software - lynx
    yum: name=lynx state=latest
  - name: log all packages installed on the system
    command: yum list installed
    register: installed_packages
  - debug: var=installed_packages
  - name: date/time stamp for when the playbook ends
    command: /usr/bin/date
    register: timestamp_end
  - debug: var=timestamp_end
  handlers:
  - name: start_apache
    service: name=httpd state=restarted
