- hosts: apacheweb
  user: anthonysegretto
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time of when the playbook starts
    raw: /usr/bin/date > /home/anthonysegretto/playbook_start.log
  - name: install the apache web server
    yum: name=httpd state=latest
  - name: start the web service
    service: name=httpd state=restarted
  - name: verify that the web service is running
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install client software - telnet
    yum: name=telnet state=latest
  - name: install client software - lynx
    yum: name=lynx state=latest
  - name: log all packages installed on the system
    raw: yum list installed > /home/anthonysegretto/installed.log
  - name: date/time stamp for when the playbook ends
    raw: /usr/bin/date > /home/anthonysegretto/playbook_end.log
